### ISSUE TITLE
🤖📯 Updates

### ISSUE THREAD

**Issue by gr2m** [wip/app#89]
I strongly advice to subscribe to this issue if you use the WIP GitHub App. I’ll post about plans for new features and changes so you can make your voice heard before we accidentally break your favorite use case :) I will also post here in case there is any security incident (See our [Security Policy](https://github.com/wip/policies/blob/master/SECURITY.md)).

The issue is locked in order to limit the noise for subscribers. Please [open a new issue](https://github.com/wip/app/issues/new) if you have any questions or feedback about an update.

## About myself 👋

Hello there, I’m Gregor! 

Besides the WIP App, I’m maintaining a few JavaScript/Node projects like [nock](https://github.com/node-nock), [semantic-release](https://github.com/semantic-release) and the official GitHub Platform Toolkit for JavaScript & Node: [octokit.js](https://github.com/octokit/octokit.js).

I’m passionate about [welcoming and inclusive communities](http://hood.ie/blog/welcoming-communities) and see it as main responsibility to encourage and support contributions of all kind. The WIP APP itself is open source and contributions of all kind are welcome, _especially_ for documentation, translations, design and user support.

You can follow and contact me directly on Twitter: [@gr2m](https://twitter.com/gr2m).

**Comment by gr2m** [comment]
I’m submitting WIP to the marketplace. I hope it will become an even better reference app that way, not only regarding the code, but also requirements such as [policies](https://github.com/wip/policies) and my answers to all the questions that GitHub will ask you when you submit your own app.

You can follow the progress of the code changes at https://github.com/wip/app/pull/94. I’d particularly appreciate your input to how configuration will work (#96).

There will be a change of how the app works and I’m not yet clear how the transition will work exactly. It’s one of the things I’ll make sure to document for y’all :)

**Comment by gr2m** [comment]
Here is a sneak preview of the upcoming WIP app, featuring

- configuration (see #96)
- checks
- custom actions

Enjoy

[![youtube video screenshot](https://user-images.githubusercontent.com/39992/42131801-87f2b7ca-7cbf-11e8-890e-f13363a36a58.png)](https://youtu.be/hLkyjpeavHA)

**Comment by gr2m** [comment]
Quick update: the new version is deployed now, the WIP should be listed in the marketplace soon. Before it’s listed I will add the request for the additional permissions. Stay tuned :)

**Comment by gr2m** [comment]
<a name="hello-marketplace"></a>

# Hello, Marketplace!

[![WIP on the GitHub Marketplace](https://user-images.githubusercontent.com/39992/47393709-1dbb6a80-d6d5-11e8-8327-bb3f8b7401e1.png)](https://github.com/marketplace/wip)

WIP is now on the GitHub marketplace: https://github.com/marketplace/wip 🎉

I want to thank you all for using WIP, for your questions, bug reports and ideas 💐 

## Changes

**First things first**: WIP is still the same app. You do not need to uninstall/install anything.

<table>
  <thead>
    <tr>
      <th></th>
      <th>Pre-Marketplace</th>
      <th>Free Plan</th>
      <th>Pro Plan</th>
    </tr>
  </thead>
  <tr>
    <th>Locations</th>
    <td>
      <ul>
        <li>Title</li>
        <li>labels</li>
        <li>commit subjects</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>Title</li>
      </ul>
    </td>
    <td>configurable via <code>.github/wip.yml</code></td>
  </tr>
  <tr>
    <th>Terms</th>
    <td>
      <ul>
        <li>WIP</li>
        <li>work in progress</li>
        <li>do not merge</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>WIP</li>
        <li>work in progress</li>
        <li>:construction:</li>
      </ul>
    </td>
    <td>configurable via <code>.github/wip.yml</code></td>
  </tr>
  <tr>
    <th>Explanation for pending status</th>
    <td>
      <center>❌</center>
    </td>
    <td>
      <center>✅</center>
    </td>
    <td>
      <center>✅</center>
    </td>
  </tr>
  <tr>
    <th>Manual overwrite</th>
    <td>
      <center>❌</center>
    </td>
    <td>
      <center>❌</center>
    </td>
    <td>
      <center>✅</center>
    </td>
  </tr>
</table>

Find usage details in [repository’s README](https://github.com/wip/app#usage).

## Notes

- **Accept the new permissions requested by the WIP app**

  You might need to accept the [new permissions requested by the WIP app](https://github.com/apps/wip/installations/new) for your account and organizations. The app will continue to work as before for a transition period, but eventually I will remove the legacy code.

- **Getting the Pro Plan features for free**

  WIP is a not-for-profit project and I will donate all revenue from the Pro Plan to [Rails Girls Summer of Code](https://railsgirlssummerofcode.org/).

  Until the WIP is [listed on the marketplace](https://github.com/marketplace/wip) or if you cannot pay for the Pro plan, you can send a pull request to add your account or organization with an explanation to the [pro-plan-for-free.js](https://github.com/wip/app/blob/master/pro-plan-for-free.js) file.

- **Legacy Commit Status Override**

  Unfortunately, when setting a pull request state using a check that has the same context name as a commit status, one does not override the other, instead they are both listed. That means that a previous "pending" commit status can block a pul pull_request indefinitely, as the new version no longer sets commit status directly, but instead is using checks. So for a transition period the app checks if there is a commit status set and overwrites it, Unfortunately there is now way to simply delete a status instead. That’s why the app requires the read/write permission for commit status for the same transition period.

**Comment by gr2m** [comment]
# It’s been a month

We have a new logo thanks to @micahilbery! See https://github.com/wip/app/pull/143 for discussion

<p  align="center"><img alt="" src="https://user-images.githubusercontent.com/39992/48955311-1d93d200-ef02-11e8-8621-59c3b337a74e.png"></p>

Here is a screenshot of Marketplace insights. The data does not include the past two days, but good enough I guess :) 

![image](https://user-images.githubusercontent.com/39992/48954968-88dca480-ef00-11e8-9554-0207128f9a8a.png)

## What I have learned

- Many people missed the notification to accept the permissions. I’ve reached out to a few folks that didn’t to ask why they did not accept them, and none of them have seen the email. I’m not sure how to know the ration of installations that are still using the legacy permissions. Telling from the logs it’s roughly 30%.
- Some people are hesitant to accept the new permissions or install WIP because it requires write access to pull requests. The reason WIP requires it is the check action that overrides the status by adding or removing the string "@wip ready for review" from the pull request body. At the same time, nobody used the check action in the past 7 days. So I will remove that code and the required write access to pull requests and instead explain how folks can do it manually.
- Marketplace only pays out revenue ones it reaches $500 USD, so that might take a few more months
- There seems to be a memory leak in Probot.

## Things I plan to work on next month

- Remove custom check actions and requiring pull request write access.
- Add timing to the logs. I’d like how long it takes to handle the pull request webhooks under different states. Once I have a baseline, I want to look into replacing the REST API calls with GraphQL and see what difference it makes.
- Making the status text more useful. Instead of just showing `in progress – Work in progress` I’d like to show something like `in progress – "WIP" found in title`
- Update the documentation to explain how you can configure WIP in a central place for an installation, you can do that by creating a `.github` repository and put a `.github/wip.yml` file in there. This became possible via https://github.com/probot/probot-config/pull/16

**Comment by gr2m** [comment]
# Still WIP

I’m sorry for the lack of updates. I’ve been busy providing for my family and in February, [GitHub announced the new Pull Request Draft feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/). I honestly wasn’t sure if people would still be interested in WIP after that, but it looks like they do:

![image](https://user-images.githubusercontent.com/39992/58723493-0b05c400-838f-11e9-882d-659f4f2ece69.png)

I’m still waiting for the first payout! I’ll pass it on to [Rails Girls Summer of Code](https://railsgirlssummerofcode.org/) as promised. Stay tuned!

So just to make it official, I’ll give the WIP some love today and am looking for things you’d be interested in. I'll start with some chore work

- [ ] #147 Remove custom check actions and requiring pull request write access
- [ ] #124 Officially deprecate the legacy support: nudge people to accept write permission for check runs in order to continue using WIP.
- [ ] #152 Maybe: add support for check boxes

**Comment by gr2m** [comment]
<h1 align=center>Happy birthday 🎈</h1>

![birthday small](https://user-images.githubusercontent.com/39992/59081333-5f82d500-88a2-11e9-8f4c-51fb473a28e7.jpg)

Wow, what a year it has been. These three little humans entered my life shortly after the tiny WIP GitHub App started its adventure to get listed on the Marketplace. WIP is older, but today in 2018 I decided that WIP is more than a little hack running on [Glitch](https://glitch.com/) (I still love you, Glitch 🎏). It became a legit GitHub App.

Its [very first commit](https://github.com/wip/app/commit/f5b6acbaa5768a4ef8acf3d44c623553940e47ce) is nearly two years old. The very first working version from that day had [barely 20 lines of code](https://github.com/wip/app/commit/a44fb7e6c3445a0486dfff1f6a7e8d80e30f2501). That version makes a great example for a minimal GitHub App if you would like to build one yourself!

Over time I added new features. Besides looking for only "WIP" in the title, the app started to [look for related terms](https://github.com/wip/app/commit/7fbd6ee) and in other places ([commit subjects](https://github.com/wip/app/commit/2d6181b) and [labels](https://github.com/wip/app/commit/77aacc8)).

More and more people started to use WIP and a few optimizations became necessary. Instead of setting a status each time, [I started to check if the status changed first](https://github.com/wip/app/commit/76070f4), as rate limits for mutating requests are much more strict.

Around that time I made the decision to submit WIP to the marketplace. Version 3 - the marketplace edition - was finally released on October 13th. Our triplets just turned one month old and I have no recollection of how I managed to accomplish that 🤔

WIP was always meant to be an experiment that everyone can use and learn from. I wanted to make sure that everyone who cannot pay for a paid plan but would benefit from its features can do so, by enabling the [pro-plan-for-free](https://github.com/wip/app/commit/7e5a195) workaround. Thank you all for being fair 💜

The marketplace edition also introduced the usage of [check runs](https://developer.github.com/v3/checks/runs/) instead of just setting commit status. It faced an interesting challenge, because it required new permissions. I didn’t want to break WIP for people who couldn't accept the new permissions (or simply missed it, like many do I fear). So I kept the old version alive [as a legacy handler](https://github.com/wip/app/commit/3e1285ff7f25f7c1429fcac7e4d6bfb5a9114373#diff-90222c578bb23acff827f2915626f7e3R59). I only replaced it a few days ago, [the new version sets the status to error and prompts to update the new permissions](https://github.com/wip/app/commit/9b4a335474dec125a32f0a0809ce3b737aa30761). Many of you saw this error and promptly accepted the new permissions. Thank you 🙏

In order to not leave you stranded with pull requests that have an error state from WIP, I also implemented a [reset of all open pull requests when you accept new permissions](https://github.com/wip/app/commit/d6603bbae9ea0d9178d9ff43aec8b809b497f074#diff-8b936660acaf3499dff7a558a1a2a39dR42). The same happens when you install the WIP or add new repositories. This only became possible thanks to the great work by @SGrondin to implement [request throttling](https://github.com/octokit/plugin-throttling.js) and [request retries](https://github.com/octokit/plugin-retry.js). [Probot](https://probot.github.io/) ships with it by default now 🚀

Looking back, I might have gotten too excited about check runs. There is a feature that allows to [request custom actions from a check run](https://developer.github.com/changes/2018-05-23-request-actions-on-checks/). I introduced a manual override action. It required write permission to pull requests which several people mentioned prevented them from installing the WIP app. I think in the past year less than 10 people used that feature, so I decided to remove it again. One permission less 👍

Somewhere in between [GitHub introduced draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/). At first I thought WIP’s day were counted, and I took a break from it to see how usage would change. But it doesn’t look like the draft feature is a full replacement. WIP is going strong and I’m confident that it’s here to stay 😊

Oh yes, it’s WIP’s birthday, and look what we got: the very first payout! 🤑

![image](https://user-images.githubusercontent.com/39992/59081511-547c7480-88a3-11e9-9ebf-3e051e9498fb.png)

As promised, I’m donating 100% of the revenue to [Rails Girls Summer of Code](https://railsgirlssummerofcode.org/). Talking about it, [RGSoC is taking a breath and are working on their rebranding](https://railsgirlssummerofcode.org/blog/2019-03-21-the-future-of-rgsoc). I for one am very excited to see what its future brings and will continue to support their outstanding work.

<p align=center>Thank you all for using WIP ❤️💚💙</p>

**Comment by gr2m** [comment]
Dear WIP pro users, I'm planning on donating WIP's revenue to a new project moving forward. Please chime in on the discussion at https://github.com/wip/app/issues/215 if you have any questions or concerns.

**Comment by gr2m** [comment]
# What's up

<a href="https://wip.vercel.app/stats"><img width="1107" alt="Screenshot of the work-in-progress app's dashboard" src="https://user-images.githubusercontent.com/39992/102722893-142fec00-42b9-11eb-9791-1fd25b7aa8a8.png"></a>

👆 The above screenshot is a live dashboard of data logged from the WIP app. I wrote [a short blog post about how I put it together](https://dev.to/gr2m/how-i-created-a-public-dashboard-for-the-wip-github-app-using-logflare-6ae). It only has data since December 13, so the comparison to the previous week is not yet very useful. But it's fascinating nevertheless, and I like how transparent the WIP becomes thanks to it. And surprising simple to put together. Please comment on my blog post above if you have any questions!

There have also been some over newsworthy updates:

1. Thanks to [Probot v11](https://github.com/probot/probot/releases/v11.0.0), the WIP app is now deployed as a serverless app to [Vercel](https://vercel.com/?utm_source=wip&utm_campaign=oss). The required change was trivial. The [Probot app function](https://github.com/wip/app/blob/1c2ac48a37b9527635a79b9d5408a53907ec2b9d/index.js) did not require any changes at all, which also means that I can run the app locally using Probot's built-in server, which makes testing and debugging much easier, and it does not require an internet connection (unlike `vercel dev`). The only two additions were:

   1. An API function at [api/index.js](https://github.com/wip/app/blob/1c2ac48a37b9527635a79b9d5408a53907ec2b9d/api/index.js). WIP's app function is a bit more complicated because it implements a redirect for [wip.vercel.app](wip.vercel.app/), the minimal amount of code would be

      ```js
      const { createNodeMiddleware, createProbot } = require("probot");
      const app = require("../");
      module.exports = createNodeMiddleware(app, { probot: createProbot() });
      ```

      We've spent a lot of time on Probot to make this possible and to make the upgrade path smooth. If you use Probot today, make sure to update and to report back!

   2. A [vercel.json](https://github.com/wip/app/blob/1c2ac48a37b9527635a79b9d5408a53907ec2b9d/vercel.json) file in order to redirect `POST /` requests to the function in `api/index.js`

2. After two years, I removed the code for handling legacy installations that still didn't accept the new permissions. There were still 323 such installations, barely any of which was active in recent weeks. Fair to say the owners of installations would have never accepted the new permissions, so I used the new [`DELETE /app/installations/{installation_id}`](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#delete-an-installation-for-the-authenticated-app) endpoint to simply remove them myself. 

   My goal for the WIP remains to be a reference application of a real-life GitHub application, and I'm glad I could finally remove code that added a non-significant amount of complexity.

3. Lastly, I'm happy to report that there I received 3 payouts for WIP's marketplace subscriptions which totaled to 1810.14 

   <img width="1920" alt="image" src="https://user-images.githubusercontent.com/39992/102723416-979f0c80-42bc-11eb-910e-8920045a9228.png">

   I used $600 to directly support members of the team who made [p5.js transition to a rotating leadership model](https://medium.com/processing-foundation/making-space-for-the-future-of-p5-js-d3c6bd3da9ac) possible. I just donated the rest

   <img width="1200" alt="image" src="https://user-images.githubusercontent.com/39992/102723633-1ea0b480-42be-11eb-9176-4d97519ca960.png">

   If you would like to join me supporting the most amazing [p5.js](https://p5js.org/) project, their holiday fundraiser is open until Dec 31, and they have some beautiful perks you can get: https://donorbox.org/supportp52020

Moving forward, I want to be as transparent with the revenue as I am with other WIP data. Stay tuned for project ["open purse"](https://github.com/gr2m/open-purse)!
